name: libsimple_flutter
description: sqlite fts5 libsimple tokenizer plugin.libsimple
version: 0.0.10
homepage: https://github.com/nay-kang/sqlite3_fts_libsimple

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.6
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.17
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  assets:
    - assets/sqlite/
  plugin:
    platforms:
      android:
        package: net.codeedu.libsimple_flutter
        pluginClass: LibsimpleFlutterPlugin
      ios:
        pluginClass: LibsimpleFlutterPlugin
      web:
        pluginClass: LibsimpleFlutterWeb
        fileName: libsimple_flutter_web.dart
